import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useRef, useState } from 'react';
import { AudioLines, Camera, ChevronDown, ChevronLeft, ChevronRight, Image, Plus, Smile, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AppMenu, Avatar, EmptyState, metadata, PhoneShell, RichMessage } from '@/components/messages-ui';
import { getConversations, useMessages } from '@/lib/messages';
export const Route=createFileRoute('/conversation/$phone')({head:()=>metadata('Conversation','Received demo messages grouped by sender.'),component:Conversation});
function Conversation(){const {phone}=Route.useParams();const {messages,ready,markRead}=useMessages();const group=getConversations(messages).find(g=>g.phone===phone);const bottom=useRef<HTMLDivElement>(null);const [draft,setDraft]=useState('');const [notice,setNotice]=useState('');
 useEffect(()=>{if(ready)markRead(phone);},[phone,ready,messages]);
 useEffect(()=>{bottom.current?.scrollIntoView();},[phone,group?.messages.length]);
 return <PhoneShell><header className="screen-header"><Button asChild variant="tool" className="icon-control"><Link to="/" aria-label="Back"><ChevronLeft/></Link></Button><Avatar/><h1>{group?.latest.sender||phone}</h1><UserRound size={20} className="text-contact-blue"/><Button asChild variant="tool" className="icon-control"><Link to="/contacts" aria-label="View contacts"><ChevronDown/></Link></Button><AppMenu/></header><div className="app-content thread-content">{group?group.messages.map((m,i)=><div key={m.id}>{(i===0||group.messages[i-1]?.date!==m.date)&&<div className="date-separator">{new Date(`${m.date}T12:00:00`).toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</div>}<article className="message-line"><div className="message-bubble"><RichMessage text={m.content} className={m.content.length>250?'clamped':''}/>{m.content.length>250&&<Button asChild variant="tool" className="view-all"><Link to="/message/$id" params={{id:m.id}}>View all<ChevronRight/></Link></Button>}</div><time className="timestamp">{m.time}</time></article></div>):<EmptyState>{ready?'No messages':'Loading messages…'}</EmptyState>}<div ref={bottom}/></div>{notice&&<div className="text-muted-foreground text-sm px-5 py-2" role="status">{notice}</div>}<div className="message-composer"><Button variant="tool" className="icon-control" aria-label="Gallery" title="Gallery" onClick={()=>setNotice('Attachments are unavailable in this local demo.')}><Image/></Button><Button variant="tool" className="icon-control" aria-label="Camera" title="Camera" onClick={()=>setNotice('Camera is unavailable in this local demo.')}><Camera/></Button><Button asChild variant="tool" className="icon-control"><Link to="/demo-messages/$id" params={{id:"new"}} aria-label="Add received message"><Plus/></Link></Button><div className="composer-input"><input aria-label="Message draft" value={draft} onChange={e=>setDraft(e.target.value)}/><Button variant="tool" className="icon-control" aria-label="Emoji" title="Emoji" onClick={()=>setDraft(draft+'☺')}><Smile/></Button></div><Button variant="samsung" className="icon-control" aria-label="Voice message" title="Voice message" onClick={()=>setNotice('Voice messages are unavailable in this local demo.')}><AudioLines/></Button></div></PhoneShell>;
}