import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useEffect, useState, type FormEvent } from 'react';
import { Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { EmptyState, Header, metadata, PhoneShell, StorageError } from '@/components/messages-ui';
import { useMessages } from '@/lib/messages';
export const Route=createFileRoute('/demo-messages/$id')({head:()=>metadata('Received Message','Create or edit a demo received message on this device.'),component:MessageForm});
function MessageForm(){const {id}=Route.useParams();const {messages,ready,save}=useMessages();const navigate=useNavigate();const existing=messages.find(m=>m.id===id);const isNew=id==='new';const [sender,setSender]=useState('');const [phone,setPhone]=useState('');const [content,setContent]=useState('');const [date,setDate]=useState('');const [time,setTime]=useState('');
 useEffect(()=>{if(existing){setSender(existing.sender);setPhone(existing.phone);setContent(existing.content);setDate(existing.date);setTime(existing.time);}else if(isNew){const now=new Date();setDate(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`);setTime(`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`);}},[existing,isNew]);
 function submit(e:FormEvent){e.preventDefault();if(!phone.trim()||!content.trim()||!date||!time)return;if(save({id:isNew?crypto.randomUUID():id,sender:sender.trim()||phone.trim(),phone:phone.trim(),content:content.trim(),date,time,unread:existing?.unread??true}))navigate({to:'/demo-messages'});}
 return <PhoneShell><Header title={isNew?'Add Received Message':'Edit Received Message'} back="/demo-messages"/><div className="app-content"><StorageError/>{ready&&!isNew&&!existing?<EmptyState>Message not found</EmptyState>:<form className="message-form" onSubmit={submit}><label>Sender name<input className="field" value={sender} onChange={e=>setSender(e.target.value)} autoComplete="off" placeholder="Sender name"/></label><label>Phone number<input className="field" type="tel" required value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="off" placeholder="Phone number"/></label><label>Message content<textarea className="field" required value={content} onChange={e=>setContent(e.target.value)} placeholder="Message"/></label><div className="date-time-fields"><label>Date<input type="date" className="field" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" className="field" required value={time} onChange={e=>setTime(e.target.value)}/></label></div><Button type="submit" size="lg" disabled={!ready}><Check/>Save</Button></form>}</div></PhoneShell>;
}