import { createFileRoute, Link } from '@tanstack/react-router';
import { ListFilter, MessageCirclePlus, Plus, Search, X } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { AppMenu, Avatar, BottomTabs, EmptyState, metadata, PhoneShell, StorageError } from '@/components/messages-ui';
import { getConversations, useMessages } from '@/lib/messages';
export const Route=createFileRoute('/')({head:()=>metadata('Conversations','Your locally stored demo message conversations.'),component:Conversations});
function Conversations(){
 const {messages,ready}=useMessages(); const [card,setCard]=useState(true);const [search,setSearch]=useState(false);const [query,setQuery]=useState('');const [unreadOnly,setUnreadOnly]=useState(false);const [person,setPerson]=useState(false);
 const unread=messages.filter(m=>m.unread).length;
 const groups=getConversations(messages).filter(g=>(!unreadOnly||g.unread>0)&&(!person||!/^\d+$/.test(g.latest.sender))&&g.messages.some(m=>`${m.sender} ${m.phone} ${m.content}`.toLowerCase().includes(query.toLowerCase())));
 return <PhoneShell><div className="app-content">{card&&<section className="unread-card"><Button variant="samsung" className="icon-control close-card" aria-label="Dismiss unread card" onClick={()=>setCard(false)}><X/></Button><h1>{unread} unread {unread===1?'message':'messages'}</h1><Button variant="samsung" className="pill-control" onClick={()=>setUnreadOnly(!unreadOnly)}>{unreadOnly?'View all':'View'}</Button></section>}<div className="list-tools"><Button variant={unreadOnly?'samsung':'tool'} className="icon-control" aria-label="Filter unread messages" title="Filter unread messages" aria-pressed={unreadOnly} onClick={()=>setUnreadOnly(!unreadOnly)}><ListFilter/></Button><Button variant="tool" className="icon-control" aria-label="Search" title="Search" onClick={()=>setSearch(!search)}><Search/></Button><AppMenu/></div>{search&&<div className="search-field"><input autoFocus className="field" aria-label="Search conversations" placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/><Button variant="tool" className="icon-control" aria-label="Clear search" onClick={()=>setQuery('')}><X/></Button></div>}<div className="category-tabs"><Button variant="tool" className={`category-tab ${!person?'selected':''}`} onClick={()=>setPerson(false)}>All</Button><Button variant="tool" className={`category-tab ${person?'selected':''}`} onClick={()=>setPerson(true)}>Person</Button><Button asChild variant="tool" className="icon-control"><Link to="/demo-messages/$id" params={{id:"new"}} aria-label="Add received message"><Plus/></Link></Button></div><StorageError/>{groups.length>0?<section className="conversation-list" aria-label="Conversations">{groups.map(g=><Link key={g.phone} to="/conversation/$phone" params={{phone:g.phone}} className="conversation-row"><Avatar/><div className="row-body"><div className="row-heading"><span className="sender">{g.latest.sender||g.phone}</span><time className="timestamp">{g.latest.time}</time></div><div className="preview-line"><span className="message-preview">{g.latest.content}</span>{g.unread>0&&<span className="unread-badge">{g.unread}</span>}</div></div></Link>)}</section>:<EmptyState>{ready?'No conversations':'Loading messages…'}</EmptyState>}</div><Button asChild variant="samsung" className="compose-fab"><Link to="/demo-messages/$id" params={{id:"new"}} aria-label="New message" title="New message"><MessageCirclePlus/></Link></Button><BottomTabs active="conversations"/></PhoneShell>;
}